name: postgres

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mercurio
      POSTGRES_USER: mercurio
      POSTGRES_PASSWORD: mercurio
