name: middleware

services:
  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg18-trixie
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mercurio
      POSTGRES_USER: mercurio
      POSTGRES_PASSWORD: mercurio
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - "9090:8080"
    environment:
      KC_DB: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://postgres:5432/mercurio
      KC_DB_USERNAME: mercurio
      KC_DB_PASSWORD: mercurio
      KC_DB_SCHEMA: public
    command:
      - start-dev
    extra_hosts:
      host.docker.internal: "host-gateway"
