spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mercurio
    username: mercurio
    password: mercurio
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/logisto
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/logisto
        registration:
          keycloak:
            client-id: lg-backend
            client-secret: HtIZKBgCt4m1QRFyf5PKO8NZAb8EvrDC
            authorization-grant-type: client_credentials

application:
  rest:
    mc-user-service:
      url: http://localhost:8082
